### PR TITLE
Fix bug

### LINKED ISSUE #5: Switching themes breaks Comet theme
To reproduce the bug

1. Click theme selector
image
2. Click any theme other than comet
3. Change the theme back to comment
# Comet working properly
image
# Comet when reproducing the bug
image

### PR DESCRIPTION
**Pull request by imdevarsh**
Probably fixes #5

### CODE REVIEW

**Review by Darth-Ness — CHANGES_REQUESTED** [review]
The problem with this is, that the themes are in alphabetical order. Instead, you could try using something like this https://www.geeksforgeeks.org/how-to-set-the-default-value-for-an-html-select-element/

**Comment by imdevarsh** [comment]
@Darth-Ness should be ready!

**Review by Darth-Ness — CHANGES_REQUESTED** [review]
Can you put it back in order?

**Review by Darth-Ness — APPROVED** [review]
Thank you! Merging in a second :)

**Pull request merged**
